[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mlops_sqldetect"
version = "0.0.1"
description = "Unsupervized SQL attack detection with MLflow tracking."
authors = [
  { name = "gquetel", email = "gregor.quetel@telecom-paris.fr" },
]
license = { file = "LICENSE" }
keywords = ["machine learning", "MLOps"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python :: 3",
]
readme = "README.md"
requires-python = "==3.14.3"
dependencies = [
  "joblib",
  "mlflow-skinny==3.12",  # Server is 3.12 so far.
  "python-dotenv",
  "numpy",
  "pandas",
  "scikit-learn",
  "torch==2.12.0",  
  "transformers==5.12.0",  
  "typer",
  "plotly",
  "kaleido",
]

[dependency-groups]
dev = [
  "pytest",
  "coverage",
  "mypy",
  "invoke",
  "mkdocs-material",
  "mkdocstrings-python",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
  "B",   # Likely bugs and design problems (flake8-bugbear)
  "E",   # PEP 8 codestyle errors
  "N",   # PEP 8 Variable naming convention
  "S",   # Security rules (flake8-bandit) 
  "W",   # PEP 8 codestyle  warnings
  "I",   # Sort imports properly (isort)
]

[tool.ruff.lint.per-file-ignores]
# assert is acceptable in testing code (not invoked with optimization)
"tests/**/*.py" = ["S101"]

[tool.ruff.format]
quote-style = "double"

[tool.coverage.run]
source = ["src/mlops_sqldetect"]
omit = ["tests/*"]
